[package]
name = "tdk_persist"
homepage = "https://bitcoindevkit.org"
version = "0.3.0"
repository = "https://github.com/bitcoindevkit/bdk"
documentation = "https://docs.rs/tdk_persist"
description = "Types that define data persistence of a BDK wallet"
keywords = ["bitcoin", "wallet", "persistence", "database"]
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = ["Bitcoin Dev Kit Developers"]
edition = "2021"
rust-version = "1.67"

[dependencies]
anyhow = { version = "1", default-features = false }
tdk_chain = { path = "../chain", version = "0.15.0", default-features = false }

[features]
default = ["tdk_chain/std", "miniscript"]
serde = ["tdk_chain/serde"]
miniscript = ["tdk_chain/miniscript"]
