[package]
name = "tdk_esplora"
version = "0.14.0"
edition = "2021"
homepage = "https://bitcoindevkit.org"
repository = "https://github.com/chaintope/tdk"
documentation = "https://docs.rs/tdk_esplora"
description = "Fetch data from esplora in the form that accepts"
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tdk_chain = { path = "../chain", version = "0.15.0", default-features = false }
esplora-client = { git = "https://github.com/chaintope/rust-esplora-client", branch="change_tapyrus_to_bitcoin", default-features = false }
async-trait = { version = "0.1.66", optional = true }
futures = { version = "0.3.26", optional = true }

# use these dependencies if you need to enable their /no-std features
tapyrus = { git = "https://github.com/chaintope/rust-tapyrus", branch = "update_on_bitcoin_0.31.x", default-features = false }
miniscript = { version = "11.0.0", optional = true, default-features = false }

[dev-dependencies]
tdk_testenv = { path = "../testenv", default-features = false }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }

[features]
default = ["std", "async-https", "blocking-https-rustls"]
std = ["tdk_chain/std"]
async = ["async-trait", "futures", "esplora-client/async"]
async-https = ["async", "esplora-client/async-https"]
async-https-rustls = ["async", "esplora-client/async-https-rustls"]
blocking = ["esplora-client/blocking"]
blocking-https-rustls = ["esplora-client/blocking-https-rustls"]
